server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jalithadewapura/config-store
          default-label: main
          search-paths:
            - 'service-config/*service'